on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test 1
        uses: ./
        id: test
        with:
          string: 'aasdfa/v1.0.1'
          pattern: '[\w\d/]*v(\d+(?:\.\d+)*)'
          replace: '$1'
      - name: Check equality 1
        run: '[[ "${{ steps.test.outputs.result }}" == "1.0.1" ]]'
      - name: Branch
        run: echo $GITHUB_REF
      - name: Test 2
        uses: ./
        id: test2
        with:
          string: "${GITHUB_REF}"
          pattern: 'refs\/head\/'
          replace: ''
      - name: Check equality 2
        run: '[[ "${{ steps.test2.outputs.result }}" == "master" ]]'
